spring:
  datasource:
    url: jdbc:mysql://myblog.mysql.database.azure.com/myblog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jaewon
    password: Zmfhdnwm0=
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    aws:
      credentials:
        access-key: # 이부분 수정필요
        secret-key:  # 이부분 수정 필요
      s3:
        bucket: thisismyblogbucket
      region:
        static: ap-northeast-2
  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: wodnjs3580@gmail.com
    password: obdu eesn zwin qamv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  level:
    org:
      springframework:
        web: TRACE
        security: TRACE